import Route from '@ember/routing/route';
import { hash } from 'rsvp';

export default class FormRoute extends Route {
  model() {
    return hash({
      itemSelected: {
        CETcode: 750720000,
        description:
          'This works, but there is a more ergonomic way to do this: grid areas.',
      },
      currencies: [
        'AED',
        'AUD',
        'BRL',
        'CAD',
        'CFA',
        'CHF',
        'CNY',
        'CVE',
        'CZK',
        'DKK',
        'EGP',
        'ETB',
        'EUR',
        'FCF',
        'GBP',
        'GHS',
        'GMD',
        'GNF',
        'HKD',
        'HUF',
        'IDR',
        'ILS',
        'INR',
        'JPY',
        'KES',
        'KRW',
        'LRD',
        'MAD',
        'MAK',
        'MUR',
        'MXN',
        'MYR',
        'NGN',
        'NOK',
        'PHP',
        'PKR',
        'PLN',
        'RUB',
        'SAR',
        'SDG',
        'SEK',
        'SGD',
        'SLL',
        'THB',
        'TND',
        'TRY',
        'TWD',
        'USD',
        'WAU',
        'XAF',
        'XDR',
        'XOF',
        'ZAR',
        'ZMK',
      ],
    });
  }
}
